name: bigcan
favicon: null
layout_spectrum: 0.9186977052595466
typography_spectrum: 0.975756575120613
title: Life of Keng & Maggie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.09346509841270745
  lightness: 0.3537510388996452
  saturation: 0.03917040815576911
  rhythmicContrast: 0.3200098071247339
purpose: []
