name: bigcan
favicon: null
layout_spectrum: 0.00811
typography_spectrum: 0.24775
title: Life of Keng & Maggie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2957b9'
    - '#8c8482'
    - '#020202'
    - '#dddfeb'
    - '#e2c055'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
